# Generated by Django 4.2.26 on 2025-12-01 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
