# Generated by Django 4.2.26 on 2025-12-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybackend', '0003_remove_userprofile_image_url_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin (ผู้ดูแลระบบ)'), ('seller', 'Seller (คนขายของ)'), ('user', 'User (ลูกค้าทั่วไป)')], default='user', max_length=20),
        ),
    ]
