# Generated by Django 4.2.27 on 2025-12-12 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybackend', '0004_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='job_title',
        ),
    ]
